---
# description: create and initialize repos in my owm private Git server

  - name: create private GIT repositories on the GIT user account
    become: yes
    become_user: git
    file:
       path: "{{ item }}"
       state: directory
    with_items:
      - /home/git/Password.git
      - /home/git/Private.git
      - /home/git/Wiki.git
      - /home/git/Professional.git

  - name: initialize GIT repositories
    become: yes
    become_user: git
    command:
      cmd: git -C "{{ item }}" init --bare
    with_items:
      - /home/git/Password.git
      - /home/git/Private.git
      - /home/git/Wiki.git
      - /home/git/Professional.git

# end of task list
