---
  - name: install TMUX Terminal MUltipleXer
    become: yes
    ansible.builtin.package:
      name:
        - tmux
      state: present
           
  - name: check if .tmux is a regular file or link to its repo counterpart
    ansible.builtin.file:
      src: /home/jorge/Documentos/DotFiles/tmux/tmux.conf.headless
      dest: /home/jorge/.tmux.conf
      state: link
      force: yes

  - name: clone the Tmux Plugin Manager from GitHub
    ansible.builtin.git:
      repo: https://github.com/tmux-plugins/tpm
      dest: ~/.tmux/plugins/tpm 
      clone: yes
      update: yes

  - name: is TMUX already running?
    ansible.builtin.shell:
      cmd: pgrep tmux
    register: tmux_status
    ignore_errors: yes
    failed_when: "tmux_status.rc == 2"
    changed_when: false

  - name: install all tpm-managed plugins (when tmux is stopped)
    ansible.builtin.shell:
      cmd: ~/.tmux/plugins/tpm/bin/install_plugins
    when: "tmux_status.rc == 1" 

  - name: install all tpm-managed plugins (when tmux is running)
    ansible.builtin.shell:
      cmd: tmux source ~/.tmux.conf && ~/.tmux/plugins/tpm/bin/install_plugins
    when: "tmux_status.rc == 0" 

  - name: append tmux starting sequence to .bashrc
    ansible.builtin.blockinfile:
      path: /home/jorge/.bashrc
      block: "{{ lookup('ansible.builtin.file', '/home/jorge/Documentos/Private/bash/bashrc.patch-tmux') }}"
      backup: yes

# end of tasks list
