---
  - name: install GNU's PASS password manager
    become: yes
    ansible.builtin.package:
      name:
        - pass
      state: present

  - name: clone password store from my private repo
    ansible.builtin.git:
      repo: 'git@{{ main_server }}:Password.git'
      dest: ~/.password-store
      clone: yes
      # update: yes
      accept_hostkey: yes

#  - name: trust my own imported keys
#    ansible.builtin.shell:
#      cmd: gpg --edit-keys ""

      # pass init "GPG-ID" 
      # pass git init
      # pass git clone git@cloudbox:Password.git

# end of tasks list
