---
  # description: list of essential packages for command line use 
  #
  # - pass
  # - acl
  # - rsync
  # - neofetch
  # - nmap (Utility for network discovery and security auditing)
  # - hexedit (hexadecimal/ASCII editor)
  # - imagemagick (necessary for Nextcloud support)

  - name: install packages ACL, CURL, HDPARM, HEXEDIT, IMAGEMAGICK, HTOP, NEOFETCH, NMAP, PARTED, RSYNC, UNRAR-FREE, UNZIP and ZIP
    become: yes
    ansible.builtin.package:
      name:
         - acl
         - curl
         - hdparm
         - hexedit
         - htop
         - imagemagick
         - neofetch
         - nmap
         - parted
         - rsync
         - unrar-free
         - unzip
         - zip
      state: present

  - ansible.builtin.import_tasks: cli-pass.yml
  - ansible.builtin.import_tasks: cli-vim.yml
  - ansible.builtin.import_tasks: cli-tmux.yml

# End of tasks list
