---
# description: tune up the filesystem placing essential files, folders and symlinks

  - name: backup the original /etc/hosts
    become: yes
    ansible.builtin.copy:
      remote_src: yes
      src: /etc/hosts
      dest: /etc/hosts.backup

  - name: add LagunaGFX's homelab/farm list of hosts to /etc/hosts
    become: yes
    ansible.builtin.blockinfile:
      path: /etc/hosts
      block: "{{ lookup('file', '~/Documentos/Private/etc/hosts.lagunagfx') }}"
      # prepend_newline: true (NOT SUPPORTED UNTIL Ansible Core 2.16)
      state: present

  - name: check for package GIT
    become: yes
    ansible.builtin.package:
      name:
        - git
      state: present

  - name: if folder ".config" is not present, then create it
    file:
       path: /home/jorge/.config
       state: directory

  - name: if folder "Documentos" is not present, then create it
    file:
       path: /home/jorge/Documentos
       state: directory

  - name: check if folder "/home/jorge/Documentos/DotFiles" exists
    ansible.builtin.stat:
      path: /home/jorge/Documentos/DotFiles
    register: folder_dotfiles

  - name: clone public GIT repos "DotFiles"
    ansible.builtin.git:
      repo: https://github.com/lagunagfx/DotFiles
      dest: /home/jorge/Documentos/DotFiles
    when: folder_dotfiles.stat.exists == false

  - name: check if .gitconfig is a regular file or its repo counterpart
    ansible.builtin.file:
      src: ~/Documentos/DotFiles/git/{{ git_config }}
      dest: ~/.gitconfig
      state: link
      force: yes

  - name: check if folder "/home/jorge/Documentos/Scripts" exists
    ansible.builtin.stat:
      path: /home/jorge/Documentos/Scripts
    register: folder_scripts

  - name: clone public GIT repos "Scripts"
    ansible.builtin.git:
      repo: https://github.com/lagunagfx/Scripts
      dest: /home/jorge/Documentos/Scripts
    when: folder_dotfiles.stat.exists == false
  
  - name: "link ~/.local/bin with ~/Documentos/Scripts"
    ansible.builtin.file:
      src: ~/Documentos/Scripts
      dest: ~/.local/bin
      state: link
      force: yes

# end of task list
