# description: completely disable ipv6 support in Debian
#              ipv6 protocol could be completely enabled back removing the changes and rebooting
---

  - name: edit '/etc/sysctl.conf' (a reboot is necessary)
    become: yes
    ansible.builtin.blockinfile:
      path: /etc/sysctl.conf
      insertafter: EOF
      block: |
        net.ipv6.conf.all.disable_ipv6 = 1
        net.ipv6.conf.default.disable_ipv6 = 1
        net.ipv6.conf.lo.disable_ipv6 = 1
        net.ipv6.conf.tun0.disable_ipv6 = 1

# end of task list
