---
  # description: essential python modules 

  - name: install basic python3 developer support
    become: yes
    ansible.builtin.package:
      name:
        - python3
        - python3-setuptools
        - python3-pip
      state: present

# End of tasks list
