---
  # description: list of essential packages for command line use 
  #
  # - pass
  # - acl
  # - rsync
  # - neofetch
  # - nmap (Utility for network discovery and security auditing)
  # - hexedit (hexadecimal/ASCII editor)

  - name: Check for packages ACL, RSYNC, NEOFETCH, HEXEDIT
    become: yes
    ansible.builtin.package:
      name:
         - acl
         - rsync
         - htop
         - unrar
         - neofetch
         - hexedit
      state: present

  - ansible.builtin.import_tasks: setup-cli-pass.yml
  - ansible.builtin.import_tasks: setup-cli-vim.yml
  - ansible.builtin.import_tasks: setup-cli-git.yml
  - ansible.builtin.import_tasks: setup-cli-tmux.yml

# End of tasks list
