---
  - name: install GNU's PASS password manager
    become: yes
    ansible.builtin.package:
      name:
        - pass
      state: present

  - name: clone .password-store from my private repo      
    ansible.builtin.git:
      repo: [git@www.lagunalabs.eu:1186]:Password.git
      dest: ~/.password-store 
      clone: yes
      update: yes

  - name: trust my own imported keys
    ansible.builtin.shell:
      cmd: gpg --edit-keys ""

# end of tasks list
