---
  # description: list of essential packages for command line use 
  #
  # - pass
  # - acl
  # - rsync
  # - neofetch
  # - nmap (Utility for network discovery and security auditing)
  # - hexedit (hexadecimal/ASCII editor)

  - name: Check for packages PASS, ACL and RSYNC
    become: yes
    ansible.builtin.package:
      name:
         - pass
         - acl
         - rsync
      state: present

  - ansible.builtin.import_tasks: setup-cli-vim.yml
  - ansible.builtin.import_tasks: setup-cli-tmux.yml

# End of tasks list
