---
  - name: install and configure GIT
    become: yes
    ansible.builtin.package:
      name:
        - git
      state: present
           
  - name: check if .gitconfig is a regular file or link to its repo counterpart
    ansible.builtin.file:
      src: ~/Documentos/DotFiles/git/gitconfig.linux-server
      dest: /home/jorge/.gitconfig
      state: link
      force: yes

# end of tasks list
