---
  # description: generate both public and private keys for SSH connection authentification

  - name: check if SSH ECDSA keys are present
    stat:
      path: "~/.ssh/id_ecdsa"
    register: sshkeys

  - name: if absent, then generate SSH ECDSA keys
    openssh_keypair:          
      path: "~/.ssh/id_ecdsa"
      type: ecdsa
      size: 521
      state: present
      force: no
    when: sshkeys.stat.exists == false

# end of task
