---
# description:

  - name: getting rid of some old Jack and Pulseaudio dependencies in favour of Pipewire
    become: yes
    ansible.builtin.package:
      name:
        - manjaro-pulse
        - pulseaudio-zeroconf
        - pulseaudio-jack
        - pulseaudio-alsa
        - pulseaudio-bluetooth
        - pulseaudio-ctl
        - pulseaudio
        - a2jmidid
        - qjackctl
        - carla
      state: absent

  - name: enable realtime support for better audio latencies
    become: yes
    ansible.builtin.package:
      name:
        - realtime-privileges
        - jack-example-tools
      state: present

  - name: add user to the 'realtime' group
    become: yes
    ansible.builtin.user:
      name: jorge
      append: true
      groups: realtime

  - name: install various essential JACK tools
    become: yes
    ansible.builtin.package:
      name:
        - jack_capture
        - meterbridge
        - non-mixer
      state: present

# end of task
