---
# description: AUR based packages for ARCH LINUX derivatives

  # seafile-client
  # 

  # Renoise install:
  #
  # > scp www.lagunagfx.eu:Software/linux/1.paid/daw/Renoise/3.4.2/* .

  # dependencies for proper abcde mp3 encoder work...
  #
  # > pacman -S python-eyed3 glyr ¿libdiscid?
  # > paru -S abcde-musicbrainz-meta

  - name: install SunVox tracker
    become: yes
    become_user: aurbuilder
    kewlfft.aur.aur:
      use: paru
      name: sunvox
      state: present

# end of tasks
