---
# description: AUR based packages for ARCH LINUX derivatives

  # seafile-client
  # losslesscut-bin
  # 
  # vdhcoapp-bin (Video Download Helper coapp)

  # Renoise install:
  #
  # scp www.lagunagfx.eu:Software/linux/1.paid/daw/Renoise/3.4.2/* .

# end of tasks
