---
# description: AUR based packages for ARCH LINUX derivatives

  # seafile-client
  # losslesscut-bin
  # 
  # vdhcoapp-bin (Video Download Helper coapp)

# end of file
  # description: specific tools for Arch based distros 
  #
  # - paru (requires rust)
  #
  #- name: [ARCH-based only] Check for packages Rust (dependency for Paru)

# End of tasks
