---
# description:

  - name: install Grafx2, a Deluxe Paint clone
    become: yes
    ansible.builtin.package:
      name:
        - grafx2
      state: present

  - name: install Inkscape, Blender and Kicad
    become: yes
    ansible.builtin.package:
      name:
        - blender
        - inkscape
        - kicad
        - kicad-library
        - kicad-library-3d
      state: present
    when: inventory_hostname not in groups['netbook']

  - name: install the Chuck programming language
    become: yes
    ansible.builtin.package:
      name:
        - chuck
      state: present

  # Chuck's mini-audicle IDE won't install form the AUR

  - name: install the Ardour DAW
    become: yes
    ansible.builtin.package:
      name:
        - ardour
      state: present

  - name: install the Reaper DAW
    become: yes
    ansible.builtin.package:
      name:
        - reaper
        - reapack
        - sws
      state: present

  - name: install Yet Another VST Bridge for MS Windows audio plugins
    become: yes
    ansible.builtin.package:
      name:
        - yabridge
        - yabridgectl
      state: present

  - name: install FastTracker, ProTracker and ImpulseTracker clones
    become: yes
    ansible.builtin.package:
      name:
        - pt2-clone
        - ft2-clone
        - schismtracker
      state: present

  - name: install MilkyTracker and GoatTracker
    become: yes
    ansible.builtin.package:
      name:
        - milkytracker
        - goattracker
      state: present

  - name: install Klystrack Plus and Furnace trackers in alpha/beta stage
    become: yes
    ansible.builtin.package:
      name:
        - klystrack-plus
        - furnace
      state: present

  - name: install virtual instruments 'Cardinal','Dexed', 'Geonkick', 'SurgeXT' and 'Helm'.
    become: yes
    ansible.builtin.package:
      name:
        - cardinal
        - dexed
        - geonkick
        - helm-synth
        - surge-xt
      state: present
    when: inventory_hostname not in groups['netbook']

  - name: make sure the Jack standalone versions of the LSP plugin suite are removed
    become: yes
    ansible.builtin.package:
      name:
        - lsp-plugins
        - lsp-plugins-standalone
        - lsp-plugins-ladspa
      state: absent

  - name: install FX plugins 'dragonfly-reverb', and the Calf and LSP plugins suite (NOT the Jack standalone versions)
    become: yes
    ansible.builtin.package:
      name:
        - dragonfly-reverb
        - calf
        - lsp-plugins-docs
        - lsp-plugins-vst
        - lsp-plugins-lv2
        - lsp-plugins-clap
      state: present

  - name: install Polyphone SoundFont editor
    become: yes
    ansible.builtin.package:
      name:
        - polyphone
      state: present

  - name: remove Tutka MIDI sequencer, which doesn't seem to run at the moment (2024·01·24)
    become: yes
    #become_user: aurbuilder
    #kewlfft.aur.aur:
    #  use: paru
    ansible.builtin.package:
      name:
        - tutka
      state: absent

  - name: audio plugins from the AUR: Repeater, the CHOWdhury Suite, 
    become: yes
    become_user: aurbuilder
    kewlfft.aur.aur:
      use: paru
      name:
        - regrader.lv2-git
        - chowbyop-bin
        - chowcentaur-bin
        - chowkick-bin
        - chowmatrix-bin
        - chowmultitool-bin
        - chowphaser-bin
        - chowtapemodel-bin  
      state: present

# end of task
