---
# description: install music composition tools

  - name: enable JACK support
    become: yes
    ansible.builtin.package:
      name:
        - realtime-privileges
        - jack-example-tools
        - a2jmidid
        - qjackctl
        - pulseaudio-jack
      state: present

  - name: install various essential JACK tools
    become: yes
    ansible.builtin.package:
      name:
        - jack_capture
        - meterbridge
        - non-mixer
      state: present

  - name: add user to the 'realtime' group
    become: yes
    ansible.builtin.user:
      name: jorge
      append: true
      groups: realtime

  - name: install the Chuck programming language
    become: yes
    ansible.builtin.package:
      name:
        - chuck
      state: present

  # Chuck's mini-audicle IDE won't install form the AUR

  - name: install the Ardour DAW
    become: yes
    ansible.builtin.package:
      name:
        - ardour
      state: present

  - name: install the Reaper DAW
    become: yes
    ansible.builtin.package:
      name:
        - reaper
        - reapack
        - sws
      state: present

  - name: install Yet Another VST Bridge for MS Windows audio plugins
    become: yes
    ansible.builtin.package:
      name:
        - yabridge
        - yabridgectl
      state: present

  - name: install FastTracker, ProTracker and ImpulseTracker clones
    become: yes
    ansible.builtin.package:
      name:
        - pt2-clone
        - ft2-clone
        - schismtracker
      state: present

  - name: install MilkyTracker and GoatTracker
    become: yes
    ansible.builtin.package:
      name:
        - milkytracker
        - goattracker
      state: present

  - name: install Klystrack Plus and Furnace trackers in alpha/beta stage
    become: yes
    ansible.builtin.package:
      name:
        - klystrack-plus
        - furnace
      state: present

  - name: install virtual instruments 'Cardinal','Dexed', 'Geonkick', 'SurgeXT' and 'Helm'.
    become: yes
    ansible.builtin.package:
      name:
        - cardinal
        - dexed
        - geonkick
        - helm-synth
        - surge-xt
      state: present

  - name: install FX plugins 'dragonfly-reverb'
    become: yes
    ansible.builtin.package:
      name:
        - dragonfly-reverb
      state: present

# end of task
