---
# description: LagunaGFX default 'distro' of Manjaro, using OpenBpx Window Manager

  - name: install the OpenBox window manager
    become: yes
    ansible.builtin.package:
      name:
        - openbox
        - picom
        - tint2
        - jgmenu
        - nitrogen
        - rofi
        - feh
        - conky
        - volumeicon
        - alacritty
      state: present

  - name: install a backlight adjustment utility (for laptops)
    become: yes
    ansible.builtin.package:
      name:
        - xorg-xbacklight
      state: present
    when: inventory_hostname not in groups['desktop']


  # for any Manjaro i3-based installations, erase all leftovers

  - name: erase all traces (if any) of the i3 window manager
    become: yes
    ansible.builtin.package:
      name:
        - i3-wm
        - i3lock
        - i3status-manjaro
        - i3exit
        - i3-scrot
        - i3-help
        - i3-default-artwork
        - artwork-i3
        - conky-i3
      state: absent

  # Remove certain problematic packages
  # gtk-desktop-portal-gnome slows down PDF opening
  - name: remove some conflicting packages
    become: yes
    ansible.builtin.package:
      name:
        - xdg-desktop-portal-gnome
      state: absent

  - name: Link LagunaGFX themes
    ansible.builtin.file:
      src: ~/Documentos/DotFiles/themes
      dest: ~/.themes
      state: link
      force: yes

  - name: Link GTK3 settings
    ansible.builtin.file:
      src: ~/Documentos/DotFiles/gtk/gtk-3.0/bookmarks
      dest: ~/.config/gtk-3.0/bookmarks
      state: link
      force: yes

  - name: Link Openbox settings
    ansible.builtin.file:
      src: ~/Documentos/DotFiles/openbox/lagunagfx
      dest: ~/.config/openbox
      state: link
      force: yes
  
  - name: Link Picom compositor settings
    ansible.builtin.file:
      src: ~/Documentos/DotFiles/picom/manjaro.defaults
      dest: ~/.config/picom
      state: link
      force: yes

  - name: Link Tint2 settings
    ansible.builtin.file:
      src: ~/Documentos/DotFiles/tint2/
      dest: ~/.config/tint2
      state: link
      force: yes

  - name: Link JGMenu settings
    ansible.builtin.file:
      src: ~/Documentos/DotFiles/jgmenu/manjaro.lagunagfx
      dest: ~/.config/jgmenu
      state: link
      force: yes

  - name: Link Conky settings
    ansible.builtin.file:
      src: ~/Documentos/DotFiles/conky
      dest: ~/.config/conky
      state: link
      force: yes
  
    # XFCE associated setup quirks

  - name: Link XFCE default applications info
    ansible.builtin.file:
      src: ~/Documentos/DotFiles/xfce4/lagunagfx/helpers.rc
      dest: ~/.config/xfce4/helpers.rc
      state: link
      force: yes
  
    # for the latest Manjaro installs, stay with LibreOffice

  - name: remove OnlyOffice suite from the system
    become: yes
    ansible.builtin.package:
      name:
         - onlyoffice-desktopeditors
      state: absent

  # Use XFCE's Thunar as file browser (PCmanFM is cool but got some interface issues)

  - name: set Thunar as default file browser
    become: yes
    ansible.builtin.package:
      name:
        - thunar
        - thunar-archive-plugin
        - thunar-media-tags-plugin 
        - thunar-volman
      state: present

  # System TuneUp: avoid screen tearing when using intel graphics card

  - name: avoid screen tearing when using SNA acceleration on intel cards
    become: yes
    ansible.builtin.blockinfile:
      path: /etc/X11/xorg.conf.d/20-intel.conf
      create: yes
      block: |
        Section "Device"
          Identifier "Intel Graphics"
          Driver "intel"
          Option "TearFree" "true"
        EndSection      
  
  - name: "install Google's signature family of fonts"
    become: yes
    ansible.builtin.package:
      name: ttf-roboto
      state: present
 
  # set Gtk3 preferences using xfce's xfconf tool

# - name: set GTK3 theme to VARIABLE
#   command:
#     xfconf-query -c xsettings -p /Net/ThemeName -s Matcha-dark-sea

# - name: set GTK3 icon theme to VARIABLE
#   command:
#     xfconf-query -c xsettings -p /Net/IconThemeName -s Papirus-Dark-Maia

# - name: set GTK3 font to VARIABLE
#   command:
#     xfconf-query -c xsettings -p /Gtk/FontName -s "Roboto 10"

# - name: set GTK3 monospace font to VARIABLE
#   command:
#     xfconf-query -c xsettings -p /Gtk/MonospaceFontName -s "DejaVu Sans Mono 10"

# - name: set GTK3 cursor theme to VARIABLE
#   command:
#     xfconf-query -c xsettings -p /Gtk/CursorThemeName -s xcursor-breeze

# end of task
