---
# description: install wine and its most needed accesories

  - name: "install 'wine-staging' branch of the WINE is Not an Emulator project"
    become: yes
    ansible.builtin.package:
      name:
        - wine-staging
        - winetricks
      state: present

  - name: "create a Wine Cellar folder"
    ansible.builtin.file:

# end of task
