---
# description: emulation/virtualization software

  # Microsoft Windows emulation through WINE

# - name: "remove standard 'wine' branch of the WINE is Not an Emulator project, if present"
#   become: yes
#   ansible.builtin.package:
#     name:
#       - wine
#     state: absent

  - name: "install 'wine-staging' branch of the WINE is Not an Emulator project"
    become: yes
    ansible.builtin.package:
      name:
        - wine-staging
        - winetricks
      state: present

  - name: "create a Wine Cellar folder"
    ansible.builtin.file:
      path: ~/.local/share/wineprefix
      state: directory

  # RetroArch :
  # install Libretro global support through RETROARCH

  - name: install Retroarch plus XMB and Ozone assets
    become: yes
    ansible.builtin.package:
      name:
        - retroarch
        - retroarch-assets-xmb
        - retroarch-assets-ozone
      state: present

  # paru -S libretro-stella

  - name: install Libretro cores
    become: yes
    ansible.builtin.package:
      name:
        - libretro-beetle-pce
        - libretro-mame2016
      state: present

  - name: install MAME tools (for chdman)
    become: yes
    ansible.builtin.package:
      name:
          - mame-tools
      state: present

  - name: install Commodore Amiga emulation
    become: yes
    ansible.builtin.package:
      name:
        - fs-uae
        - fs-uae-launcher
      state: present
    when: ansible_hostname not in groups['netbook']

  - name: install Atari emulation
    become: yes
    ansible.builtin.package:
      name:
        - hatari
      state: present
    when: ansible_hostname not in groups['netbook']

#  - name: enable Retroarch's Online Updater
#    ansible.builtin.lineinfile

    # menu_show_core_updater = "true"
    # rgui_browser_directory = "~/Documentos/ROMs"

# End of tasks
