# description
---

  - name: install Retroarch plus XMB and Ozone assets
    become: yes
    ansible.builtin.package:
      name:
        - retroarch
        - retroarch-assets-xmb
        - retroarch-assets-ozone
      state: present

  # paru -S libretro-stella

  - name: install Libretro cores
    become: yes
    ansible.builtin.package:
      name:
        - libretro-beetle-pce
        - libretro-mame2016
      state: present

  - name: install MAME tools (for chdman)
    become: yes
    ansible.builtin.package:
      name:
          - mame-tools
      state: present

#  - name: enable Retroarch's Online Updater
#    ansible.builtin.lineinfile

    # menu_show_core_updater = "true"
    # rgui_browser_directory = "~/Documentos/ROMs"

# end of task
