---
# description:
# - Setup files, folders and links for a proper desktop use
# - Depends on previous changes made by "common/tasks/filesystem.yml"

  - name: Are GTK3 settings linked to the global LagunaGFX settings
    ansible.builtin.file:
      src: ~/Documentos/DotFiles/gtk/gtk-3.0/bookmarks
      dest: ~/.config/gtk-3.0/bookmarks
      state: link
      force: yes

# end of task list
