---
  # description: set Gtk3 preferences using xfce's xfconf tool

  - name: set GTK3 theme to VARIABLE
    command:
      xfconf-query -c xsettings -p /Net/ThemeName -s Matcha-dark-sea

  - name: set GTK3 icon theme to VARIABLE
    command:
      xfconf-query -c xsettings -p /Net/IconThemeName -s Papirus-Maia

  - name: set GTK3 font to VARIABLE
    command:
      xfconf-query -c xsettings -p /Gtk/FontName -s "Roboto 10"

  - name: set GTK3 monospace font to VARIABLE
    command:
      xfconf-query -c xsettings -p /Gtk/MonospaceFontName -s "DejaVu Sans Mono 10"

  - name: set GTK3 cursor theme to VARIABLE
    command:
      xfconf-query -c xsettings -p /Gtk/CursorThemeName -s xcursor-breeze

# end of tasks list
