---
  # description: specific tools for Arch based distros 
  #
  # - paru (requires rust)

  - name: [ARCH-based only] Check for packages Rust (dependency for Paru)
    become: yes
    ansible.builtin.package:
      name:
         - onlyoffice-desktopeditors
      state: absent

# End of tasks list
