# description: system tweaks
---

    # install optional tools

  - name: install optional GPU tools
    become: yes
    ansible.builtin.package:
      name:
        - mesa-utils
        - vulkan-tools
      state: present

    # avoid screen tearing when using intel graphics card

  - name: avoid screen tearing when using SNA acceleration on intel cards
    become: yes
    ansible.builtin.blockinfile:
      path: /etc/X11/xorg.conf.d/20-intel.conf
      create: yes
      block: |
        Section "Device"
          Identifier "Intel Graphics"
          Driver "intel"
          Option "TearFree" "true"
        EndSection        
    when: ( inventory_hostname in groups['laptop'] ) and ( inventory_hostname != 'badulaque' )

# End of tasks
