# description: system tweaks
---

    # avoid screen tearing when using intel graphics card

  - name: avoid screen tearing when using SNA acceleration on intel cards
    become: yes
    ansible.builtin.blockinfile:
      path: /etc/X11/xorg.conf.d/20-intel.conf
      create: yes
      block: |
        Section "Device"
          Identifier "Intel Graphics"
          Driver "intel"
          Option "TearFree" "true"
        EndSection        
    when: inventory_hostname in groups['laptop']

# End of tasks
