# description: XFCE / GTK3 settings both for it and other GTK-based WMs
---

  - name: Link GTK3 settings
    ansible.builtin.file:
      src: ~/Documentos/DotFiles/gtk/gtk-3.0/bookmarks
      dest: ~/.config/gtk-3.0/bookmarks
      state: link
      force: yes
      
  - name: Link XFCE default applications
    ansible.builtin.file:
      src: ~/Documentos/DotFiles/xfce4/lagunagfx/helpers.rc
      dest: ~/.config/xfce4/helpers.rc
      state: link
      force: yes

    # install Google's Roboto font

  - name: install Google's signature family of fonts
    become: yes
    ansible.builtin.package:
        name:
          - ttf-roboto
          - ttf-roboto-mono-nerd
        state: present

    # set Gtk3 preferences using xfce's xfconf tool

  - name: set XFWM4 theme to Matcha-dark-sea
    command:
      xfconf-query -c xfwm4 -p /general/theme -s Matcha-dark-sea

  - name: "set XFCE4 workspaces to 4"
    command:
      xfconf-query -c xfwm4 -p /general/workspace_count -t int -s 4

  - name: "set XFCE4 workspace names to 1,2,3 and 4"
    command:
      xfconf-query -c xfwm4 -p /general/workspace_names -t string -t string -t string -t string -s "1" -s "2" -s "3" -s "4"

  - name: set GTK3 theme to VARIABLE
    command:
      xfconf-query -c xsettings -p /Net/ThemeName -s Matcha-dark-sea

  - name: set GTK3 icon theme to VARIABLE
    command:
      xfconf-query -c xsettings -p /Net/IconThemeName -s Papirus-Dark-Maia

  - name: set GTK3 font to VARIABLE
    command:
      xfconf-query -c xsettings -p /Gtk/FontName -s "Roboto 10"

  - name: set GTK3 monospace font to VARIABLE
    command:
      xfconf-query -c xsettings -p /Gtk/MonospaceFontName -s "RobotoMono Nerd Font Mono 10"

  - name: set GTK3 cursor theme to VARIABLE
    command:
      xfconf-query -c xsettings -p /Gtk/CursorThemeName -s xcursor-breeze

# end of tasks
