#!/bin/sh
/usr/sbin/sed -i 's/^Name\[es\]\=Nextcloud\ cliente\ de\ sincronización\ de\ escritorio/Name\[es\]\=Nextcloud/' /usr/share/applications/com.nextcloud.desktopclient.nextcloud.desktop
/usr/sbin/sed -i 's/^Categories\=Utility\;X-SuSE-SyncUtility\;/Categories\=Network\;FileTransfer\;/' /usr/share/applications/com.nextcloud.desktopclient.nextcloud.desktop
