---
# description: LagunaGFX's global playbook for system configuration 

  - hosts: all

    vars:
      # global variables applicable to this scope
      main_server: "{{ 'cloudbox' if inventory_hostname in groups['inside'] else 'www.lagunagfx.eu:1187' }}"
      tmux_config: "{{ 'tmux.conf.headless' if inventory_hostname in groups['server'] else 'tmux.conf.desktop' }}"
      ipv6_enabled: true

    tasks:

       - name: print Ansible facts
         debug:
           msg: 
             - " hostname: {{ ansible_facts['hostname'] }}"
             - "   distro: {{ ansible_facts['distribution'] }}"
             - "inventory: {{ inventory_hostname }}"

#      - ansible.builtin.import_tasks: roles/common/tasks/ssh-generate-keys.yml
       - ansible.builtin.import_tasks: roles/common/tasks/filesystem.yml
       - ansible.builtin.import_tasks: roles/common/tasks/cli.yml
#      - ansible.builtin.import_tasks: roles/server/tasks/git-private.yml
#        when: inventory_hostname == 'cloudbox'

  - name: import global Playbook for desktop and laptop graphical workstations
    ansible.builtin.import_playbook: gui.yml
    when: ansible_facts['hostname'] in groups['graphical']

# end of playbook
