---
# description: desktop and laptop customization

  - ansible.builtin.import_tasks: roles/gui/tasks/internet.yml
  - ansible.builtin.import_tasks: roles/gui/tasks/intel-graphics.yml
  - ansible.builtin.import_tasks: roles/gui/tasks/filesync.yml
  - ansible.builtin.import_tasks: roles/gui/tasks/hexchat.yml
  - ansible.builtin.import_tasks: roles/gui/tasks/media-video.yml

  - name: debug GROUPS
    debug:
      var: groups['graphical']

  - ansible.builtin.import_tasks: roles/gui/tasks/creation.yml
    when: ansible_facts['hostname'] in groups['graphical']
  - ansible.builtin.import_tasks: roles/gui/tasks/emulation.yml

# end of playbook
