---
# file: server_web.yml
# description: custom changes to deploy a Web Server instance 

  - hosts: cloudbox

    vars:

      # global variables applicable to this scope

      ipv6_enabled: true
      www_root: /var/www

    tasks:

#      - ansible.builtin.import_tasks: roles/common/tasks/ipv6.yml
#      - ansible.builtin.import_tasks: roles/common/tasks/filesystem.yml
#      - ansible.builtin.import_tasks: roles/common/tasks/ssh-generate-keys.yml
#      - ansible.builtin.import_tasks: roles/common/tasks/cli.yml
#      - ansible.builtin.import_tasks: roles/server/tasks/git-private.yml
#      - ansible.builtin.import_tasks: roles/common/tasks/python.yml
     
      # server specific tasks

      # ToDo! : Replace the 'force: no' condition when copying samba and transmission configs

      - ansible.builtin.import_tasks: roles/server/tasks/zfs.yml
#     - ansible.builtin.import_tasks: roles/server/tasks/dnsmasquing.yml
#     - ansible.builtin.import_tasks: roles/server/tasks/ansible.yml
#     - ansible.builtin.import_tasks: roles/server/tasks/filesystem-server.yml
#     - ansible.builtin.import_tasks: roles/server/tasks/service-nginx.yml
#     - ansible.builtin.import_tasks: roles/server/tasks/service-mariadb.yml
#     - ansible.builtin.import_tasks: roles/server/tasks/service-nextcloud.yml
#     - ansible.builtin.import_tasks: roles/server/tasks/service-transmission.yml
#     - ansible.builtin.import_tasks: roles/server/tasks/service-samba.yml
#     - ansible.builtin.import_tasks: roles/server/tasks/service-seafile.yml
#     - ansible.builtin.import_tasks: roles/server/tasks/service-ttrss.yml
#     - ansible.builtin.import_tasks: roles/server/tasks/service-piwigo.yml

# end of playbook
