---
  - hosts: cloudbook
    connection: local
    become: yes
    tasks:

      - name: apt upgrade
        apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

      - name: Remove useless packages from the cache
        apt:
           autoclean: yes

      - name: essential packages
        apt:
          pkg:
          - pass

      - name: base packages
        apt:
          name: nginx
          state: present

      - name: create private GIT repositories
        file:
          path: "{{ item }}"
          state: directory
        with_items:
          - /home/git/Private.git
          - /home/git/Password.git

      - name: init --bare GIT repositories
        command:
          cmd: git -C /home/git/Password.git init --bare

      - name: clone private GIT repositories
        become_user: jorge
        git:
           repo: git@cloudbook:Password.git
           dest: /home/jorge/.password-store
           clone: yes
           update: yes


  - hosts: all
    tasks:
      - name: generate SSH ECDSA keys
        openssh_keypair:          
          path: "~/.ssh/id_ecdsa"
          type: ecdsa
          size: 521
          state: present
          force: no

  - hosts: cloudbook
    tasks:
      - name: Clone a repo with separate git directory
        ansible.builtin.git:
          repo: git@cloudbook:Private.git
          dest: Private

# Essential Packages (Arch distro, command line)
#
# - vim
# - pass
# - pacaur
# - neofetch
# - nmap (Utility for network discovery and security auditing)
# - hexedit (hexadecimal/ASCII editor)

  - hosts: desktop laptop
    become: yes
    tasks:
      - name: Check for essential packages
        pacman:
          name:
            - pass 
            - vim
            - pacaur
            - neofetch
            - nmap
            - hexedit
          state: present
  - hosts: mediabook,badulaque
    become: yes
    tasks:
      - name: pacman upgrade
        pacman:
          update_cache: yes
          upgrade: yes
