---
  - hosts: badulaque,mediabook
    tasks:

       - name: install both Vim and NeoVim
         become: yes
         community.general.pacman:
           name:
             - vim
             - neovim
           state: present
           
       - name: create .vim folder
         ansible.builtin.file:
           path: /home/jorge/.vim
           state: directory
           mode: '0755'

       - name: clone VimVundle repository from GitHub
         ansible.builtin.git:
           repo: https://github.com/VundleVim/Vundle.vim.git
           dest: /home/jorge/.vim/bundle/Vundle.vim

       - name: link NeoVim's init.vim to Vim's vimrc
         ansible.builtin.file:
           src: /home/jorge/.vimrc
           dest: /home/jorge/.vim/init.vim
           state: link
       
       - name: link NeoVim's ./config/nvim to Vim's .vim folder
         ansible.builtin.file:
           src: /home/jorge/.vim
           dest: /home/jorge/.config/nvim
           state: link

       - name: install Vundle plugin
         shell: vim +PluginInstall +qall --headless

# End of Playbook

#      - name: linking GNU-PASS manager folder to the GIT Password repo
#        file:
#           path: /home/jorge/.password-store
#           src: /home/jorge/Password
#           state: link
