plugin_dirs = [
    '/home/jorge/.local/share/wineprefix/win10_audio/drive_c/Program Files/Common Files/CLAP',
    '/home/jorge/.local/share/wineprefix/win10_audio/drive_c/Program Files/Common Files/VST3',
    '/home/jorge/.local/share/wineprefix/win10_audio/drive_c/Program Files/Roland VS/JV-1080',
    '/home/jorge/.local/share/wineprefix/win10_audio/drive_c/Program Files/VSTPlugins',
    '/home/jorge/.local/share/wineprefix/winxp_32bit_audio/drive_c/Program Files/VSTPlugins',
]
vst2_location = 'centralized'
no_verify = false
blacklist = []

[last_known_config]
wine_version = 'wine-9.8 (Staging)'
yabridge_host_hash = -8601703033867957043
